services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-bsn
    restart: unless-stopped

  maildev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - 1080:1080
      - 1025:1025

#  bsn-api:
#    container_name: bsn-api
#    image: bsn/bsn:1.0.2
#    depends_on:
#      - postgres
#      - maildev
#    ports:
#      - 8088:8088
#    networks:
#      - spring-bsn

#  bsn-ui:
#    container_name: bsn-ui
#    image: bsn/bsn-ui:1.0.0
#    depends_on:
#      - bsn-api
#    ports:
#      - 8080:80
#    networks:
#      - spring-bsn

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - 9090:8080
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-bsn
    command:
      - "start-dev"

networks:
  spring-bsn:
    driver: bridge

volumes:
  postgres:
    driver: local