services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-bsn
    restart: unless-stopped

  maildev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - 1080:1080
      - 1025:1025



networks:
  spring-bsn:
    driver: bridge


volumes:
  postgres:
    driver: local